actor: Tester
paths:
    data: tests/_data
    envs: tests/_envs
    log: tests/_output
    support: tests/_support
    tests: tests
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
coverage:
  enabled: true
  include:
    - src/*
  exclude:
    - tests/*
    - vendor/*
